// This file is auto-generated by scripts/generate-build-info.mjs
export const APP_VERSION = "1.4.0";
export const BUILD_ID = "1.4.0-1772912648089";
export const BUILD_TIME = "2026-03-07T19:44:08.088Z";
export const BUILD_INFO = { version: APP_VERSION, buildId: BUILD_ID, buildTime: BUILD_TIME };
