// This file is auto-generated by scripts/generate-build-info.mjs
export const APP_VERSION = "1.3.0";
export const BUILD_ID = "1.3.0-1770735517985";
export const BUILD_TIME = "2026-02-10T14:58:37.984Z";
export const BUILD_INFO = { version: APP_VERSION, buildId: BUILD_ID, buildTime: BUILD_TIME };
