// This file is auto-generated by scripts/generate-build-info.mjs
export const APP_VERSION = "1.2.0";
export const BUILD_ID = "1.2.0-1768986655226";
export const BUILD_TIME = "2026-01-21T09:10:55.225Z";
export const BUILD_INFO = { version: APP_VERSION, buildId: BUILD_ID, buildTime: BUILD_TIME };
